import Head from 'next/head'
import Container from "../components/container/Container.comp";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <h2>Hello World</h2>
        </Container>
      </main>
    </div>
  )
}
