import styles from './index.module.scss';
import Head from 'next/head'
import Container from "../components/container/Container.comp";
import Section from "../components/section/Section.comp";
import Navbar from "../components/navbar/Navbar.comp";
import Column from "../components/column/Column.comp";
import Button from "../components/button/Button.comp";
import Footer from "../components/footer/Footer.comp";

const Index = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
      <script src="https://kit.fontawesome.com/9e7afe6829.js" crossOrigin="anonymous"/>
    </Head>

    <main>
      <Navbar/>
      <Section type="hero">
        <Container>
          <Column to={4} className={styles.occupation}>
            <h1>👋</h1>
            <h3>Hey there,</h3>
            <h1>I'm Blair Cross.</h1>
            <h2>A Scotland based student and software engineer.</h2>
          </Column>
          <Column className={styles.interests}>
            <h2>I like building user centric solutions, and AI.</h2>
            <h4>(Sometimes at the same time)</h4>
          </Column>
          <Column>
            <Button href={'/'}><h3>See what I've been up too</h3></Button>
          </Column>
        </Container>
      </Section>
      <Footer />
    </main>
  </div>
)

export default Index;
