name: Docker Image Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted
    env:
      IMAGE_NAME: bxsys/website:prod
      CONT_NAME: bxsys_web_prod

    steps:
    - uses: actions/checkout@v2

    - name: Inject Certs
      run: chmod +x inject-certs.sh ; ./inject-certs.sh

    - name: Compose Up
      run: docker-compose up --build -d
